// src/components/NetlifyIdentity.svelte
<script>

import { onMount } from 'svelte'

onMount(() => {
    if (window.netlifyIdentity) {
        window.netlifyIdentity.on('init', (user) => {
            if (!user) {
                window.netlifyIdentity.on('login', () => {
                    document.location.href = '/admin/';
                });
            }
        });
    }
})

</script>

// src/components/NetlifyIdentity.vue
<script>

export default {

    mounted() {
        if (window.netlifyIdentity) {
            window.netlifyIdentity.on('init', (user) => {
                if (!user) {
                    window.netlifyIdentity.on('login', () => {
                        document.location.href = '/admin/';
                    });
                }
            });
        }
    }

}

</script>
